const $=s=>document.querySelector(s),base=new URL('./',location.href);let age=new URLSearchParams(location.search).get('age')==='upper'?'upper':'lower',data,selected=null,state={};
const key=()=>`bibletree-demo-2026-11-01-${age}`;
function save(){try{localStorage.setItem(key(),JSON.stringify(state));}catch{}}
const captions=['친구가 다른 동네로 이사를 가요.\n“이제 매일 함께 놀 수 없겠구나…”','밤이 되어도 친구 생각에 눈물이 나요.\n슬픈 마음을 숨기지 않아도 괜찮아요.','엄마가 안아 주셨던 날이 떠올라요.\n“하나님, 제 곁에 함께할 사람을 주셔서 감사해요.”','다음 날, 친구는 여전히 보고 싶어요.\n말씀 속 다윗도 울던 때를 기억하며 하나님께 감사했어요.','“하나님, 친구가 보고 싶어요.\n제 마음을 들어 주세요. 친구도 돌봐 주세요.”','“엄마, 내 이야기 들어 줘서 고마워요.”\n슬픔 속에서도 내 마음을 나누고, 받은 사랑을 기억해요.'];
// Display the original image in six viewports, preserving all of its pixels.
const bounds=[0,320,633,968,1305,1624,2048];
$('#panels').innerHTML=captions.map((c,i)=>`<figure class="frame"><div class="panel-art" style="background:none;position:relative;overflow:hidden;aspect-ratio:683/${bounds[i+1]-bounds[i]}"><img src="assets/webtoon.png" alt="${['이사 가는 친구와 슬픈 작별','밤에 눈물 흘리는 아이','엄마가 안아 주었던 기억','아침에 성경을 읽는 아이','마음을 솔직하게 기도하는 아이','엄마와 감사의 마음을 나누는 아이'][i]}" style="position:absolute;width:100%;top:${-bounds[i]/683*100}%;left:0" ${i>1?'loading="lazy"':''}></div><figcaption class="caption">${c}</figcaption></figure>`).join('');
function wordActivity(){const upper=age==='upper';const words=upper?['기쁨','은총은 평생','아침']:['감사해요','하나님','도와주세요'];const expected=upper?['은총은 평생','아침','기쁨']:['하나님','도와주세요'];state.slots??=Array(expected.length).fill('');selected=null;const prompts=upper?['노염은 잠깐 ↔','저녁 ↔','울음 ↔']:['다윗은 힘들 때','께 부르짖었어요. “'];const a=document.createElement('div');a.className='act';a.innerHTML=`<h3>1. ${upper?'말씀 속 짝을 찾아요':'다윗의 기도에 단어를 넣어요'}</h3><p class="hint">단어를 끌어 넣거나, 단어를 누른 뒤 빈칸을 눌러요. 답을 바꾸려면 다른 단어를 골라요.</p><div class="wordbank">${words.map(w=>`<button draggable="true" data-word="${w}" aria-pressed="false">${w}</button>`).join('')}</div><div class="sentences">${expected.map((_,i)=>upper?`<p>${prompts[i]} <button class="slot" data-slot="${i}" aria-label="${prompts[i]} 짝 빈칸">빈칸</button></p>`:`${prompts[i]} <button class="slot" data-slot="${i}" aria-label="${i+1}번째 빈칸">빈칸</button>${i===1?'!”':''}`).join('')}</div><button class="check">말씀과 맞춰 보기</button><p class="feedback" role="status"></p>`;
const refresh=()=>a.querySelectorAll('[data-slot]').forEach((b,i)=>{b.textContent=state.slots[i]||'빈칸';b.classList.toggle('filled',!!state.slots[i]);});
const put=(i,w)=>{if(!words.includes(w))return;state.slots[i]=w;save();refresh();a.querySelector('.feedback').textContent='';};
a.querySelectorAll('[data-word]').forEach(b=>{b.onclick=()=>{selected=b.dataset.word;a.querySelectorAll('[data-word]').forEach(x=>x.setAttribute('aria-pressed',x===b));a.querySelector('.feedback').textContent=`‘${selected}’를 넣을 빈칸을 눌러요.`;};b.ondragstart=e=>{selected=b.dataset.word;e.dataTransfer.setData('text/plain',selected);};});a.querySelectorAll('[data-slot]').forEach((b,i)=>{b.onclick=()=>{if(selected)put(i,selected);else a.querySelector('.feedback').textContent='먼저 단어 카드를 골라 주세요.';};b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();put(i,e.dataTransfer.getData('text/plain'));};});a.querySelector('.check').onclick=()=>{a.querySelector('.feedback').textContent=state.slots.every((v,i)=>v===expected[i])?(upper?'맞아요! 다윗은 울음보다 오래가는 하나님의 은총을 노래해요.':'맞아요! 다윗은 힘들 때 하나님께 도움을 구했어요.'):'본문을 다시 보고 빈칸을 채워 볼까요?';};refresh();return a;}
function choiceActivity(){const upper=age==='upper';const opts=upper?['우리가 최고야. 이제 아무도 우리를 못 이겨.','이겨서 정말 기뻐요. 뛸 힘을 주신 하나님께 감사해요.']:['“하나님, 도와주세요.” 하고 기도해요.','하나님이 전에 도와주신 일을 떠올려요.','엄마나 선생님께 내 마음을 말해요.'];state.choices??=[];const a=document.createElement('div');a.className='act';a.innerHTML=`<h3>2. ${upper?'이긴 날에도 하나님을 기억해요':'울고 싶은 날, 나는 이렇게 해 볼래요'}</h3><p>${upper?'축구 시합에서 우리 팀이 이겼어요. 6절에서 자신을 돌아본 다윗의 고백과 더 가까운 말을 골라요.':'해 보고 싶은 일을 골라요. 여러 개 골라도 좋아요.'}</p><div class="options">${opts.map((o,i)=>`<button data-choice="${i}" aria-pressed="false">${o}</button>`).join('')}</div><p class="feedback" role="status"></p>`;const render=()=>a.querySelectorAll('button').forEach((b,i)=>{b.setAttribute('aria-pressed',state.choices.includes(i));b.classList.toggle('chosen',state.choices.includes(i));});a.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{state.choices=upper?[i]:state.choices.includes(i)?state.choices.filter(x=>x!==i):[...state.choices,i];save();render();a.querySelector('.feedback').textContent=upper?(i===1?'맞아요. 기쁨을 누리며 하나님이 하신 일을 기억해요.':'6절에서 다윗은 자신이 흔들리지 않을 거라고 했던 말을 돌아봐요. 다시 골라 볼까요?'):(state.choices.length?'좋아요. 고른 일 중 하나를 오늘 해 볼까요?':'다시 골라도 괜찮아요.');});render();return a;}
async function render(){const current=age;try{const response=await fetch(`assets/${current}.json`);if(!response.ok)throw Error('원고를 불러오지 못했어요');const result=await response.json();if(current!==age)return;data=result;try{state=JSON.parse(localStorage.getItem(key())||'{}');}catch{state={};}document.body.classList.toggle('upper',age==='upper');document.title=`${data.title} · 바이블트리`;$('#title').textContent=data.title;document.querySelectorAll('[data-age]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.age===age));$('#card-art').src=`assets/card-${age}.png`;$('#qr').src=`assets/qr-${age}.png`;$('#qr-download').href=`assets/qr-${age}.png`;$('#print-link').href=$('#print-link2').href=`print.html?age=${age}`;$('#verses').innerHTML=data.verses.map(v=>`<div class="verse ${['2','4','5'].includes(v.n)?'key':''}"><b>${v.n}</b><span>${v.t}</span></div>`).join('');$('#glossary').innerHTML=data.glossary.map(g=>`<dt>${g.word}</dt><dd>${g.def}</dd>`).join('');$('#story').innerHTML=data.story.map(p=>`<p>${p}</p>`).join('');$('#activities').replaceChildren(wordActivity(),choiceActivity());$('#deeper-prompt').textContent=age==='upper'?'4절에서 다윗은 다른 사람들에게 함께 감사하라고 불러요. 오늘 가족이나 교회 친구와 나누고 싶은 감사 한 문장을 적어 보세요.':'하나님이 도와주신 일을 떠올려요. 고마운 마음을 한 문장으로 적거나, 가족에게 말해 보세요.';$('#reflection').value=state.reflection||'';$('#prayer-text').textContent=data.prayer;$('#done-message').textContent=state.done?'오늘의 묵상을 기억했어요. 나중에 다시 와도 좋아요.':'';}catch(e){$('#title').textContent='잠시 후 다시 열어 주세요';console.error(e);}}
document.querySelectorAll('[data-age]').forEach(b=>b.onclick=()=>{age=b.dataset.age;const url=new URL(location.href);url.searchParams.set('age',age);history.replaceState({},'',url);render();});$('#reflection').oninput=e=>{state.reflection=e.target.value;save();};$('#done').onclick=()=>{state.done=true;save();$('#done-message').textContent='오늘의 묵상을 기억했어요. 나중에 다시 와도 좋아요.';};$('#reset').onclick=()=>{state={};save();render();};render();
